### ISSUE TITLE
Compatibility with TensorFlow v2.x

### ISSUE THREAD

**Issue by spothineni654** [funkey/gunpowder#182]
I saw the [gunpowder documentation](http://funkey.science/gunpowder/api.html#tensorflow-train) and it looks like TensorFlow v1, would I need to use tf.compat.v1 in TensorFlow v2 or is Gunpowder compatible with v2.x?

**Comment by pattonw** [comment]
Sorry, I haven't used tensorflow in a while. I don't think gunpowder supports tensorflow v2 yet

**Comment by spothineni654** [comment]
Alright thank you for the info!
