### ISSUE TITLE
SimpleAugment.process should iterate over keys from request

### ISSUE THREAD

**Issue by hanslovsky** [funkey/gunpowder#37]
[`SimpleAugment.process` gets array keys from batch](https://github.com/funkey/gunpowder/blob/release-v1.0/gunpowder/nodes/simple_augment.py#L87), when it would make more sense to use the keys in the request:
```python
for (array_key, array) in batch.arrays.items():
```
`SimpleAugment` should only modify the arrays in the request, not any other array that may be attached to the batch.

The most simple way to fix this would be to add a check
```python
if array_key not in request:
   continue
```
in the appropriate places. I can create a PR but would need to know if you agree on that, first.

**Comment by hanslovsky** [comment]
Alternatively, if you strongly think that the keys should be retrieved from the batch rather than the request, how about adding a `list` (defaults to `None`) that explicitly specifies which keys to use for augmentation. If `None`, use all the keys from the batch.

**Comment by funkey** [comment]
I agree that it would be better to only augment the arrays that are requested. PR welcome.

Furthermore, only the requested arrays should be kept in the `Batch`. Arrays needed only to produce a requested array (like labels for affinities) that have not been requested by the user should be dropped by the node that requested them. Overlaps with https://github.com/funkey/gunpowder/issues/16.

**Comment by hanslovsky** [comment]
> Furthermore, only the requested arrays should be kept in the `Batch`

For test purposes of new nodes, I wrote a small script that executes a pipeline and then shows the requested arrays in [payntera](https://github.com/saalfeldlab/payntera). I created a `Duplicate` that copies all selected nodes from a request, so I can easily visualize the original, unmodified data as well, using the same pipeline/request/batch. This would not work if arrays that were not requested were to be removed from the batch. As long as I do not use `RandomLocation`, the workaround is easy: I could create a second pipeline for the original data.

Another way to do this would be to add another parameter `exclude_keys=()` to `SimpleAugment` (and other use cases as well). Any `key` for which `key in exclude_keys == True` should not be augmented but also not removed from the batch. The duplicate keys would then needed to be included in the request, of course.

**Comment by funkey** [comment]
For your test case, you can just put one `Snapshot` before the `SimpleAugment`, and another one after it. This way you get both versions on the same requested arrays.

**Comment by hanslovsky** [comment]
`Snapshot` saves as hdf, though, no? I would prefer to have those arrays in memory.

**Comment by hanslovsky** [comment]
I think I will just make a `SnapshotAsDict` that stores the arrays in memory into a `dict`.
