### ISSUE TITLE
pip install does not include augment dependency

### ISSUE THREAD

**Issue by hanslovsky** [funkey/gunpowder#38]
See funkey/augment#1

**Comment by hanslovsky** [comment]
Dependencies in `install_requires` can point to a git repository. It works for me wih `pip-18.1` but I do not know what the oldest version of pip is that supports:
```python
install_requires = [
    'gunpowder',
    'scikit-image>=0.14.1',
    'numpy>=1.15.4',
    'scipy>=1.1.0',
    'daisy',
    'malis',
    'augment @ git+https://github.com/funkey/augment'
    #'z5py',
]
```
```
Collecting augment@ git+https://github.com/funkey/augment from git+https://github.com/funkey/augment (from eqip==0.2.1.dev0)
  Cloning https://github.com/funkey/augment to /tmp/pip-install-yj_iom9f/augment
```

This might be a solution to this problem, but that depends on how important support for older versions of pip/setuptools/distutils is.

**Comment by funkey** [comment]
That looks like a good solution to me. Do you want to PR against `release-v1.0`?

**Comment by hanslovsky** [comment]
Copying my post from funkey/augment#1:

I stand correct, git repositories inside `install_requires` are not a viable solution:
```sh
$ pip install fuse
Collecting fuse
  Using cached https://files.pythonhosted.org/packages/55/a1/3e9dff172d9918d4562f0acf73024cf502163febc4c1873db5967e8b2855/fuse-0.1.0.tar.gz
Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
fuse depends on augment@ git+https://github.com/funkey/augment@4a42b01ccad7607b47a1096e904220729dbcb80a 
```

The only solution is to rename augment or to integrate it into gunpowder. Otherwise no downstream packages can be made available through pypi. This should probably happen before the gunpowder-1.0 release.

**Comment by funkey** [comment]
`augment` is now available on PyPI as `augment-nd`, resolving this issue.
