### ISSUE TITLE
TypeError: __init__() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by weihuang527** [funkey/gunpowder#45]
I have built the gunpowder image using docker first. When I try to run a sample, such as [https://github.com/funkey/gunpowder/blob/master/examples/cremi/request_batch.py](https://github.com/funkey/gunpowder/blob/master/examples/cremi/request_batch.py), I get a bug:
root@28d57bb6feec:/userhome/huangwei/mala/mala/cremi# python request_batch.py 
DEBUG:gunpowder.array:Registering array key RAW
DEBUG:gunpowder.array:Registering array key GT_LABELS
DEBUG:gunpowder.array:Registering array key GT_LABELS_2
DEBUG:gunpowder.array:Registering array key GT_LABELS_4
DEBUG:gunpowder.array:Registering array key GT_IGNORE
DEBUG:gunpowder.array:Registering array key GT_AFFINITIES
DEBUG:gunpowder.array:Registering array key GT_BOUNDARY
DEBUG:gunpowder.array:Registering array key GT_BOUNDARY_GRADIENT
DEBUG:gunpowder.array:Registering array key GT_BOUNDARY_DISTANCE
DEBUG:gunpowder.array:Registering array key LOSS_SCALE
DEBUG:gunpowder.array:Registering array key ALPHA_MASK
Traceback (most recent call last):
  File "request_batch.py", line 148, in <module>
    train()
  File "request_batch.py", line 50, in train
    for sample in ['sample_A_20160501.hdf','sample_B_20160501.hdf','sample_C_20160501.hdf']
  File "request_batch.py", line 50, in <genexpr>
    for sample in ['sample_A_20160501.hdf','sample_B_20160501.hdf','sample_C_20160501.hdf']
TypeError: __init__() takes at least 2 arguments (1 given)
I don't understand it and don't know how to deal with it.
I guess it could go wrong in _Normalize()_ function or _RandomLocation()_ function.
I'd like you to tell me the some solution. Thank you very much.

**Comment by funkey** [comment]
My guess is that your docker container contains a more recent version of `gunpowder` than what the example was written for. Please have a look at the [example](https://github.com/funkey/gunpowder/blob/release-v1.0/examples/cremi/train.py) in the current `release-v1.0` development branch.

**Comment by funkey** [comment]
This example is outdated by now. We wrote new tutorials, one of them showing how to [set up a simple pipeline](http://funkey.science/gunpowder/tutorial_simple_pipeline.html) step-by-step. I hope you will find it useful.
