### ISSUE TITLE
Weird logic for provided spec in RandomProvider

### ISSUE THREAD

**Issue by cmalinmayor** [funkey/gunpowder#52]
I was searching for places where we might be iterating through dictionaries using items() and deleting elements, since this is not allowed with python3, and I found this puzzling bit of code.

https://github.com/funkey/gunpowder/blob/e6ee429ab7b3c784aaafc041d11dacfbc3a9f8ed/gunpowder/nodes/random_provider.py#L41-L49

I didn't look too closely to see what the right solution is, but deleting a key after first checking to make sure that it is not there seems wrong. If the correct solution does involve deleting elements from a dictionary while iterating over it, we should use `list(<dict>.items())`.

**Comment by funkey** [comment]
You are right, that doesn't make sense. I think the snippet above should be `common_spec` in line 47 and `provider.spec` in line 48. Then we are still left with the issue of deleting keys while iterating, which should be solved by creating a list of to-be-deleted keys and deleting them later.

Thanks for spotting that. Do you want to fix it?

**Comment by funkey** [comment]
…or create a list of specs to iterate over, similar to your fix in https://github.com/funkey/gunpowder/pull/53.

**Comment by cmalinmayor** [comment]
Yes, I can make those changes.
