### ISSUE TITLE
SimpleAugment transposes axes in the ROI request, instead of transposing the axes in the array

### ISSUE THREAD

**Issue by benjamin9555** [funkey/gunpowder#67]
If the global ROI is a subset of an entire dataset and therefore has three different offsets for x, y and z , the current transpose can lead to requests far away from the global ROI.

**Comment by funkey** [comment]
Fixed in https://github.com/funkey/gunpowder/commit/3b41136798e19fd80cd11bd00bbeb5d2243e2c44

Thanks for bringing this up!
