### ISSUE TITLE
rename attribute resolution to voxel_size

### ISSUE THREAD

**Issue by juliabuhmann** [funkey/gunpowder#8]
Currently, the attribute resolution is used to specify the size of voxels ([usually in nanometer]) of the underlying datasets/volumes. This information is important as some operations are carried out in voxel while other operations are carried out in physical space.

A renaming from resolution to voxel_size would make the meaning of this attribute more clear.

**Comment by funkey** [comment]
Done in a4ff3adf5b4fbc0eaef54489436e820aca78c385
